#!/usr/bin/env bash
# File: 7-highlander
# Description: An infinite loop script that handles SIGTERM by printing a message.

# Use trap to catch SIGTERM (signal 15) and execute a command.
# The script will continue running after the trap command is executed.
trap 'echo "I am invincible!!!"' SIGTERM

# Start the infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
