#!/usr/bin/env bash
# This script loops 1 to 10, displaying custom messages for 4 and 8, using if-elif-else.
n=1
while [ $n -le 10 ]; do
	if [ $n -eq 4 ]; then
		echo "bad luck"
	elif [ $n -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$((n + 1))
done
